language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t deedsgrom48/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true deedsgrom48/docker-react npm run test
